# -*- coding: utf-8 -*-
import json

with open(r'c:\Users\pc\Desktop\airx\src\i18n\locales\tr.json', encoding='utf-8') as f:
    tr = json.load(f)
with open(r'c:\Users\pc\Desktop\airx\src\i18n\locales\en.json', encoding='utf-8') as f:
    en = json.load(f)

# ═══════════════════════════════════════════════
# whyPage — WhyAirXPage.jsx
# ═══════════════════════════════════════════════
tr['whyPage'] = {
    'heroLine1': 'Diğerleri',
    'heroLine2': 'vaad eder.',
    'heroLine3': 'AiRX teslim eder.',
    'heroSubtitle': 'Biyometrik veri riski, donanım maliyeti ve yabancı destek kuyruğu olmadan İK yönetimi. Tam olarak böyle olmalı.',
    'heroDemoBtn': 'Demo Talep Et',
    'heroPricingBtn': 'Fiyatları İncele',
    'heroStat1Value': '150+',
    'heroStat1Label': 'Aktif Kurum',
    'heroStat1Sub': 'Türkiye genelinde',
    'heroStat2Value': '15K+',
    'heroStat2Label': 'Kullanıcı',
    'heroStat2Sub': 'Platforma bağlı',
    'heroStat3Value': '14',
    'heroStat3Label': 'Modül',
    'heroStat3Sub': 'Tek abonelikte',
    'heroStat4Value': '%99.9',
    'heroStat4Label': 'Uptime',
    'heroStat4Sub': 'SLA garantili',
    'statsLabel1': 'Aktif Kurum',
    'statsSub1': 'Türkiye genelinde',
    'statsLabel2': 'Kullanıcı',
    'statsSub2': 'Aktif çalışan',
    'statsLabel3': 'Modül',
    'statsSub3': 'Tek platformda',
    'statsLabel4': 'Uptime',
    'statsSub4': 'SLA garantisi',
    'compareTitle': 'AiRX vs. Diğer Çözümler',
    'compareSubtitle': 'Rakiplerimizi küçümsemiyoruz — sadece farkı gösteriyoruz.',
    'compareColAirx': 'AiRX',
    'compareColOthers': 'Diğerleri',
    'row1Feature': 'Biyometrik veri gerektirmez',
    'row1Note': 'KVKK tam uyum',
    'row2Feature': 'Türkçe yerel destek ekibi',
    'row2Note': "Türkiye'de yerleşik",
    'row3Feature': 'Donanım satın almadan kurulum',
    'row3Note': '1 günde hazır',
    'row4Feature': '14 modül tek platformda',
    'row4Note': 'Tümü dahil',
    'row5Feature': 'Mobil QR kod ile yoklama',
    'row5Note': 'iOS & Android',
    'row6Feature': 'Gerçek zamanlı analitik',
    'row6Note': '',
    'row7Feature': 'Özelleştirilebilir iş akışları',
    'row7Note': '',
    'row8Feature': 'Yemekhane & fiziksel erişim entegrasyonu',
    'row8Note': '',
    'row9Feature': 'SaaS — ekstra lisans maliyeti yok',
    'row9Note': '',
    'pillarsTitle': 'Her Detayda Fark',
    'pillarsSubtitle': 'Küçük detaylar büyük fark yaratır. AiRX bunu her özellikte gösterir.',
    'pillar1Label': 'Gizlilik Önce',
    'pillar1Title': 'Biyometrik Veri Yok, Tam KVKK Uyumu',
    'pillar1Body': 'Parmak izi, yüz taraması veya retina verisi sisteme hiç girmez. Mobil QR kod her şeyi halleder; çalışanlarınızın mahremiyeti korunur.',
    'pillar2Label': 'Hızlı Başlangıç',
    'pillar2Title': '24 Saat İçinde Canlıda',
    'pillar2Body': 'Ekstra donanım sipariş etmenize gerek yok. Sisteminizi bir iş günü içinde kurun, aynı gün kullanmaya başlayın. Diğer çözümler haftalarca sürer.',
    'pillar3Label': 'Her Şey Dahil',
    'pillar3Title': '14 Modül, Tek Abonelik',
    'pillar3Body': "PDKS'ten yemekhanesine, izin yönetiminden iş zekasına — ayrı lisanslar için ayrı bütçe harcamadan tüm İK süreçlerinizi tek platformda yönetin.",
    'pillar4Label': 'Gerçek Destek',
    'pillar4Title': 'Türkçe, Yerli, Hızlı',
    'pillar4Body': "Yabancı destek portallarında kaybolmak yok. Türkçe konuşan, Türkiye'de yerleşik destek ekibimiz anında yanınızda.",
    'pillar5Label': 'Büyüyen Yapı',
    'pillar5Title': "10'dan 10.000'e Kadar",
    'pillar5Body': 'Küçük işletmeden büyük kuruma aynı platform, aynı deneyim. Ekibiniz büyüdükçe AiRX de büyür — yeniden kurulum gerekmez.',
    'pillar6Label': 'Yerel Uzmanlık',
    'pillar6Title': "Türkiye'ye Özgün Tasarım",
    'pillar6Body': 'SGK, KVKK, yerel mevzuat — hepsi baştan düşünülmüş. Yabancı yazılımları yerele uyarlamakla zaman kaybetmezsiniz.',
    'quoteText': 'İK yazılımı seçmek',
    'quoteHighlight': 'stratejik bir karardır.',
    'quoteBody': 'Yanlış seçim; biyometrik veri riskleri, yıllarca süren implementasyonlar ve Türkçe bilmeyen destek ekipleri demektir. AiRX bu sorunları baştan çözerek tasarlanmıştır.',
    'quoteDemoBtn': 'Ücretsiz Demo İste',
    'quoteModulesBtn': 'Modülleri Keşfet',
}

en['whyPage'] = {
    'heroLine1': 'Others',
    'heroLine2': 'promise.',
    'heroLine3': 'AiRX delivers.',
    'heroSubtitle': 'HR management without biometric data risk, hardware cost, or foreign support queues. Exactly how it should be.',
    'heroDemoBtn': 'Request a Demo',
    'heroPricingBtn': 'View Pricing',
    'heroStat1Value': '150+',
    'heroStat1Label': 'Active Institutions',
    'heroStat1Sub': 'Across Turkey',
    'heroStat2Value': '15K+',
    'heroStat2Label': 'Users',
    'heroStat2Sub': 'Connected to platform',
    'heroStat3Value': '14',
    'heroStat3Label': 'Modules',
    'heroStat3Sub': 'In one subscription',
    'heroStat4Value': '99.9%',
    'heroStat4Label': 'Uptime',
    'heroStat4Sub': 'SLA guaranteed',
    'statsLabel1': 'Active Institutions',
    'statsSub1': 'Across Turkey',
    'statsLabel2': 'Users',
    'statsSub2': 'Active employees',
    'statsLabel3': 'Modules',
    'statsSub3': 'On one platform',
    'statsLabel4': 'Uptime',
    'statsSub4': 'SLA guarantee',
    'compareTitle': 'AiRX vs. Other Solutions',
    'compareSubtitle': "We don't belittle our competitors — we just show the difference.",
    'compareColAirx': 'AiRX',
    'compareColOthers': 'Others',
    'row1Feature': 'No biometric data required',
    'row1Note': 'Full GDPR compliance',
    'row2Feature': 'Turkish local support team',
    'row2Note': 'Based in Turkey',
    'row3Feature': 'Setup without hardware purchase',
    'row3Note': 'Ready in 1 day',
    'row4Feature': '14 modules on one platform',
    'row4Note': 'All included',
    'row5Feature': 'Attendance via mobile QR code',
    'row5Note': 'iOS & Android',
    'row6Feature': 'Real-time analytics',
    'row6Note': '',
    'row7Feature': 'Customizable workflows',
    'row7Note': '',
    'row8Feature': 'Cafeteria & physical access integration',
    'row8Note': '',
    'row9Feature': 'SaaS — no extra license cost',
    'row9Note': '',
    'pillarsTitle': 'Difference in Every Detail',
    'pillarsSubtitle': 'Small details make a big difference. AiRX demonstrates this in every feature.',
    'pillar1Label': 'Privacy First',
    'pillar1Title': 'No Biometric Data, Full GDPR Compliance',
    'pillar1Body': "Fingerprints, facial scans or retina data never enter the system. Mobile QR code handles everything; your employees' privacy is protected.",
    'pillar2Label': 'Fast Start',
    'pillar2Title': 'Live in 24 Hours',
    'pillar2Body': "No need to order extra hardware. Set up your system in one business day, start using it the same day. Other solutions take weeks.",
    'pillar3Label': 'All Inclusive',
    'pillar3Title': '14 Modules, One Subscription',
    'pillar3Body': 'From attendance to cafeteria, from leave management to business intelligence — manage all your HR processes on a single platform without separate budgets for separate licenses.',
    'pillar4Label': 'Real Support',
    'pillar4Title': 'Turkish, Local, Fast',
    'pillar4Body': "No getting lost in foreign support portals. Our Turkish-speaking, Turkey-based support team is instantly at your side.",
    'pillar5Label': 'Scalable Structure',
    'pillar5Title': 'From 10 to 10,000',
    'pillar5Body': "Same platform, same experience from small business to large enterprise. As your team grows, AiRX grows too — no reinstallation required.",
    'pillar6Label': 'Local Expertise',
    'pillar6Title': 'Designed for Turkey',
    'pillar6Body': "SGK, GDPR, local legislation — all considered from the start. No wasted time adapting foreign software to local needs.",
    'quoteText': 'Choosing an HR software',
    'quoteHighlight': 'is a strategic decision.',
    'quoteBody': 'The wrong choice means biometric data risks, years-long implementations and support teams who speak no Turkish. AiRX was designed to solve these problems from the ground up.',
    'quoteDemoBtn': 'Request a Free Demo',
    'quoteModulesBtn': 'Explore Modules',
}

# ═══════════════════════════════════════════════
# about — AboutPage.jsx
# ═══════════════════════════════════════════════
tr['about'] = {
    'heroTitle1': 'İnsan kaynaklarında',
    'heroTitleHighlight': 'daha net, daha hızlı',
    'heroTitle2': 've daha güvenli bir akış.',
    'heroSubtitle': 'AiRX, İK ekiplerinin operasyon yükünü azaltırken çalışan deneyimini de iyileştirmek için geliştirildi. Hedefimiz; dağınık süreçleri tek platformda birleştiren, mobil öncelikli ve mevzuata uyumlu bir yapı sunmak.',
    'heroBtn1': 'Değerlerimizi Keşfedin',
    'heroBtn2': 'Demo Talep Et',
    'cardQuote': 'Tek bir modül değil, birlikte çalışan bir İK ekosistemi.',
    'principle1': 'Biyometrik veri toplamadan güvenli operasyon',
    'principle2': 'Mobil öncelikli çalışan deneyimi',
    'principle3': 'Hızlı kurulum, kısa adaptasyon süresi',
    'principle4': 'Türkiye mevzuatına ve yerel ihtiyaçlara uyum',
    'quickStat1Value': '1 gün',
    'quickStat1Label': 'Hedef kurulum süresi',
    'quickStat2Value': 'Tek ekran',
    'quickStat2Label': 'Dağınık süreçler yerine',
    'statsLabel1': 'Aktif Kurum',
    'statsLabel2': 'Günlük Kullanıcı Etkileşimi',
    'statsLabel3': 'Birbirine Entegre Modül',
    'statsLabel4': 'Platform Sürekliliği Hedefi',
    'valuesSectionTitle': 'Ürünü kadar yaklaşımı da net bir ekip',
    'valuesSectionSubtitle': "AiRX'i geliştirirken yalnızca özellik listesine değil, kurumların gerçekten nasıl çalıştığına odaklanıyoruz. Her kararımızı birkaç temel ilke etrafında şekillendiriyoruz.",
    'value1Title': 'Sadelik',
    'value1Text': 'İK ekiplerinin gününü zorlaştıran değil, hızlandıran ekranlar tasarlıyoruz. Her adım daha az tıklama, daha net karar için kurgulanıyor.',
    'value2Title': 'Güven',
    'value2Text': 'KVKK uyumunu ürünün sonuna eklenen bir katman olarak değil, sistemin temel prensibi olarak ele alıyoruz. Biyometrik veri toplamadan güvenli operasyon.',
    'value3Title': 'Süreklilik',
    'value3Text': 'Kurulumdan sonraki dönem bizim için asıl başlangıç. Eğitim, destek ve ürün geliştirmeyi aynı yolculuğun parçası görüyoruz.',
    'storyQuote': 'İK operasyonunu sadece dijitalleştirmek değil, sadeleştirmek istedik.',
    'storyBody': 'AiRX; insan kaynakları, yöneticiler ve çalışanlar için ayrı ayrı değil, ortak çalışan bir deneyim olarak tasarlandı. Karmaşık süreçleri azaltan her iyileştirme, bizim için ürün başarısının en net göstergesi.',
    'miniStat1Val': '2021',
    'miniStat1Desc': 'Kuruluş yılı',
    'miniStat2Val': '14 +',
    'miniStat2Desc': 'Modül sayısı',
    'miniStat3Val': '150 +',
    'miniStat3Desc': 'Aktif kurum',
    'miniStat4Val': '1 gün',
    'miniStat4Desc': 'Kurulum hedefi',
    'milestone1Tag': 'Başlangıç',
    'milestone1Title': 'Sahadaki gerçek ihtiyacı dinledik',
    'milestone1Text': 'AiRX, masa başı varsayımlarla değil; vardiya, izin, puantaj ve erişim süreçlerinde yaşanan gerçek operasyonel sorunları çözmek için şekillendi.',
    'milestone2Tag': 'Bugün',
    'milestone2Title': 'Tek platformda bağlı bir deneyim',
    'milestone2Text': 'İzin yönetiminden ziyaretçi süreçlerine kadar farklı İK operasyonlarını tek ekranda, tek veri akışında bir araya getiriyoruz.',
    'milestone3Tag': 'Yarın',
    'milestone3Title': 'Daha akıllı, daha öngörülü araçlar',
    'milestone3Text': 'Yalnızca kayıt tutan değil, yöneticilere öneri üreten ve ekiplerin daha hızlı aksiyon almasını sağlayan bir platform inşa ediyoruz.',
    'ctaTitle': "AiRX'i merak ediyorsanız, ekibimiz size platformu memnuniyetle anlatsın.",
    'ctaSubtitle': 'Süreçlerinizi dinleyip sizin yapınıza uygun akışı birlikte kuralım. Demo, kurulum yaklaşımı ve modül yapısı için ekibimizle iletişime geçin.',
    'ctaBtn1': 'Demo Talep Et',
    'ctaBtn2': 'info@AiRX.com.tr',
}

en['about'] = {
    'heroTitle1': 'In human resources,',
    'heroTitleHighlight': 'clearer, faster',
    'heroTitle2': 'and a more secure flow.',
    'heroSubtitle': 'AiRX was developed to reduce the operational burden of HR teams while improving employee experience. Our goal: to offer a mobile-first, legally compliant structure that unifies scattered processes on a single platform.',
    'heroBtn1': 'Discover Our Values',
    'heroBtn2': 'Request a Demo',
    'cardQuote': 'Not a single module, but a working HR ecosystem.',
    'principle1': 'Secure operation without biometric data collection',
    'principle2': 'Mobile-first employee experience',
    'principle3': 'Fast setup, short adaptation period',
    'principle4': 'Compliance with Turkish regulations and local needs',
    'quickStat1Value': '1 day',
    'quickStat1Label': 'Target setup time',
    'quickStat2Value': 'Single screen',
    'quickStat2Label': 'Instead of scattered processes',
    'statsLabel1': 'Active Institutions',
    'statsLabel2': 'Daily User Interactions',
    'statsLabel3': 'Integrated Modules',
    'statsLabel4': 'Platform Continuity Target',
    'valuesSectionTitle': 'A team as clear in approach as in product',
    'valuesSectionSubtitle': "When developing AiRX, we focus not only on the feature list but on how institutions really work. We shape every decision around a few core principles.",
    'value1Title': 'Simplicity',
    'value1Text': "We design screens that speed up HR teams' days, not complicate them. Every step is structured for fewer clicks and clearer decisions.",
    'value2Title': 'Trust',
    'value2Text': "We treat GDPR compliance not as a layer added at the end of the product, but as the core principle of the system. Secure operation without biometric data collection.",
    'value3Title': 'Continuity',
    'value3Text': "The period after installation is the real beginning for us. We see training, support and product development as part of the same journey.",
    'storyQuote': 'We wanted not just to digitize HR operations, but to simplify them.',
    'storyBody': 'AiRX was designed as an experience that works together for HR, managers and employees — not separately. Every improvement that reduces complex processes is the clearest indicator of product success for us.',
    'miniStat1Val': '2021',
    'miniStat1Desc': 'Year founded',
    'miniStat2Val': '14+',
    'miniStat2Desc': 'Number of modules',
    'miniStat3Val': '150+',
    'miniStat3Desc': 'Active institutions',
    'miniStat4Val': '1 day',
    'miniStat4Desc': 'Setup target',
    'milestone1Tag': 'Beginning',
    'milestone1Title': 'We listened to real needs in the field',
    'milestone1Text': 'AiRX was shaped not from desk assumptions, but to solve real operational problems experienced in shift, leave, payroll and access processes.',
    'milestone2Tag': 'Today',
    'milestone2Title': 'A connected experience on one platform',
    'milestone2Text': 'We bring together different HR operations from leave management to visitor processes on a single screen, in a single data flow.',
    'milestone3Tag': 'Tomorrow',
    'milestone3Title': 'Smarter, more predictive tools',
    'milestone3Text': "We're building a platform that not only keeps records, but generates recommendations for managers and enables teams to take action faster.",
    'ctaTitle': "If you're curious about AiRX, our team will be happy to explain the platform to you.",
    'ctaSubtitle': 'Let us listen to your processes and set up the right workflow together. Contact our team for a demo, setup approach and module structure.',
    'ctaBtn1': 'Request a Demo',
    'ctaBtn2': 'info@AiRX.com.tr',
}

# ═══════════════════════════════════════════════
# pricing — PricingPage.jsx
# ═══════════════════════════════════════════════
tr['pricing'] = {
    'heroTitle1': 'Personel sayınızı girin,',
    'heroTitle2': 'size uygun',
    'heroTitleHighlight': 'AiRX planını',
    'heroTitle3': 'anında görün.',
    'heroSubtitle': 'Yeni fiyat yapımız çalışan aralığına göre kişi başı aylık bazda hesaplanır. Üstte personel sayınızı seçin, altta aylık, 6 aylık peşin ve yıllık peşin seçeneklerini karşılaştırın.',
    'tier1Label': '2-10 Çalışan',
    'tier2Label': '11-30 Çalışan',
    'tier3Label': '31-50 Çalışan',
    'tier4Label': '51-100 Çalışan',
    'tier5Label': '101-500 Çalışan',
    'tier6Label': '500+ Çalışan',
    'plan1Title': 'Aylık',
    'plan1Desc': 'Esnek başlangıç yapmak isteyen ekipler için standart aylık fiyat.',
    'plan2Title': '6 Aylık Peşin',
    'plan2Desc': '6 ay peşin ödeme ile %10 iskondo avantajını yakalayın.',
    'plan3Title': 'Yıllık Peşin',
    'plan3Desc': 'En güçlü birim maliyet için yıllık peşin planı seçin.',
    'staffCountLabel': 'Personel Sayısı',
    'staffSuffix': 'Personel',
    'matchedTierLabel': 'Eşleşen Kademe',
    'customTierDesc': '500+ çalışan için standart liste fiyatı yerine kurumunuza özel teklif hazırlıyoruz.',
    'customTierBadge': 'Özel Teklif Süreci',
    'perPersonBadge': 'Kişi başı bazlı hesaplama aktif',
    'perPersonMonth': 'Kişi başı / ay',
    'selectedStaff': 'Seçilen personel',
    'monthlyEquivalent': 'Aylık karşılık',
    'thisMonthTotal': 'Bu ay ödenecek',
    'upfrontTotal': 'Toplam {{duration}} ay peşin',
    'monthlyNote': 'Aylık ödeme ile hemen başlayabilir, büyüdükçe kademe fiyatına göre ilerleyebilirsiniz.',
    'upfrontNote': 'Peşin ödemede kişi başı aylık maliyet {{saving}} daha avantajlı hale gelir.',
    'customQuote': 'Özel Teklif',
    'customQuoteDesc': 'Bu plan için satış ekibimiz çalışan sayınıza, modül kapsamınıza ve kurulum yapınıza göre net teklif iletecek.',
    'customQuoteBtn': 'Teklif İste',
    'contactUs': 'İletişime geçin',
    'tableSectionTitle': 'Tüm çalışan aralıkları için net fiyat tablosu',
    'tableSectionSubtitle': 'Kişi başı aylık ücret · KDV dahil değildir',
    'colEmployeeCount': 'Çalışan sayısı',
    'colMonthly': 'Aylık',
    'colSemiAnnual': '6 Aylık Peşin',
    'discountSemi': '%10 İskonto',
    'colAnnual': 'Yıllık Peşin',
    'discountAnnual': '%15 İskonto',
    'perPerson': '/ kişi',
    'ctaTitle': 'Kurumunuza özel teklif için birlikte netleştirelim.',
    'ctaSubtitle': 'Modül kapsamı, kurulum yapısı ve 500+ çalışan senaryoları için satış ekibimiz size özel bir teklif hazırlasın.',
    'ctaBtn1': 'Teklif İste',
    'ctaBtn2': 'İletişime Geç',
}

en['pricing'] = {
    'heroTitle1': 'Enter your headcount,',
    'heroTitle2': 'instantly see the right',
    'heroTitleHighlight': 'AiRX plan',
    'heroTitle3': 'for you.',
    'heroSubtitle': 'Our new pricing structure is calculated on a per-person monthly basis by employee range. Select your headcount above, then compare monthly, 6-month prepaid and annual prepaid options below.',
    'tier1Label': '2-10 Employees',
    'tier2Label': '11-30 Employees',
    'tier3Label': '31-50 Employees',
    'tier4Label': '51-100 Employees',
    'tier5Label': '101-500 Employees',
    'tier6Label': '500+ Employees',
    'plan1Title': 'Monthly',
    'plan1Desc': 'Standard monthly price for teams that want a flexible start.',
    'plan2Title': '6-Month Prepaid',
    'plan2Desc': 'Get 10% discount advantage with 6-month prepaid payment.',
    'plan3Title': 'Annual Prepaid',
    'plan3Desc': 'Choose the annual prepaid plan for the best unit cost.',
    'staffCountLabel': 'Employee Count',
    'staffSuffix': 'Employees',
    'matchedTierLabel': 'Matched Tier',
    'customTierDesc': "For 500+ employees, we prepare a custom quote for your institution instead of the standard list price.",
    'customTierBadge': 'Custom Quote Process',
    'perPersonBadge': 'Per-person based calculation active',
    'perPersonMonth': 'Per person / month',
    'selectedStaff': 'Selected staff',
    'monthlyEquivalent': 'Monthly equivalent',
    'thisMonthTotal': 'Total for this month',
    'upfrontTotal': 'Total {{duration}} months prepaid',
    'monthlyNote': 'Start immediately with monthly payment, advance by tier price as you grow.',
    'upfrontNote': 'With prepaid payment, the monthly cost per person becomes {{saving}} more advantageous.',
    'customQuote': 'Custom Quote',
    'customQuoteDesc': 'For this plan, our sales team will provide a clear quote based on your employee count, module scope and setup structure.',
    'customQuoteBtn': 'Request a Quote',
    'contactUs': 'Contact us',
    'tableSectionTitle': 'Clear price table for all employee ranges',
    'tableSectionSubtitle': 'Fee per person per month · VAT not included',
    'colEmployeeCount': 'Employee count',
    'colMonthly': 'Monthly',
    'colSemiAnnual': '6-Month Prepaid',
    'discountSemi': '10% Discount',
    'colAnnual': 'Annual Prepaid',
    'discountAnnual': '15% Discount',
    'perPerson': '/ person',
    'ctaTitle': "Let's clarify together for your institution's custom quote.",
    'ctaSubtitle': 'Let our sales team prepare a custom quote for you for module scope, setup structure and 500+ employee scenarios.',
    'ctaBtn1': 'Request a Quote',
    'ctaBtn2': 'Contact Us',
}

# ═══════════════════════════════════════════════
# modulePage — ModulePage.jsx
# ═══════════════════════════════════════════════
tr['modulePage'] = {
    'backBtn': 'Tüm Modüller',
    'heroDemoBtn': 'Ücretsiz Demo Al',
    'heroAllModulesBtn': 'Tüm Modüller',
    'featuresTitle': '{{name}} ile neler yapabilirsiniz?',
    'featuresSubtitle': 'Her bir alan, ekibinizin iş akışında daha net kontrol, daha güçlü görünürlük ve daha hızlı uygulama deneyimi sunmak için tasarlandı.',
    'areaPrefix': 'Alan',
    'featureProvides': 'Ne Sağlar',
    'summary1': 'Operasyon akışını standartlaştırır ve günlük kontrol yükünü azaltır.',
    'summary2': 'Takibi görünür hale getirir ve ekipler için hızlı aksiyon alanı açar.',
    'summary3': 'Süreçleri ölçülebilir hale getirir ve yönetsel karar kalitesini destekler.',
    'benefitsSectionTitle': 'Somut farkı hissedin',
    'benefitsSectionSubtitle': 'AiRX {{name}} modülü, günlük operasyonel yükü azaltırken hata riskini minimuma indirir.',
    'benefitsTryBtn': 'Hemen Deneyin',
    'ctaTitle': '{{name}} modülünü ücretsiz deneyin.',
    'ctaSubtitle': 'Kurulum gerektirmez. Aynı gün aktif. Kredi kartı gerekmez.',
    'ctaDemoBtn': 'Ücretsiz Demo Al',
    'notFoundTitle': 'Modül bulunamadı',
    'notFoundLink': 'Ana sayfaya dön',
    'otherModulesTitle': 'Diğer Modüller',
    'otherModulesSubtitle': 'AiRX platformunun tüm süreçleri tek çatı altında nasıl yönettiğini keşfedin.',
    'otherModulesAllBtn': "Tüm {{count}} Modülü Gör",
}

en['modulePage'] = {
    'backBtn': 'All Modules',
    'heroDemoBtn': 'Get a Free Demo',
    'heroAllModulesBtn': 'All Modules',
    'featuresTitle': 'What can you do with {{name}}?',
    'featuresSubtitle': 'Each area is designed to provide clearer control, stronger visibility and faster application experience in your team\'s workflow.',
    'areaPrefix': 'Area',
    'featureProvides': 'What It Provides',
    'summary1': 'Standardizes the operation flow and reduces the daily control burden.',
    'summary2': 'Makes tracking visible and opens a quick action area for teams.',
    'summary3': 'Makes processes measurable and supports managerial decision quality.',
    'benefitsSectionTitle': 'Feel the concrete difference',
    'benefitsSectionSubtitle': 'AiRX {{name}} module reduces daily operational burden while minimizing the risk of errors.',
    'benefitsTryBtn': 'Try It Now',
    'ctaTitle': 'Try {{name}} module for free.',
    'ctaSubtitle': 'No installation required. Active the same day. No credit card needed.',
    'ctaDemoBtn': 'Get a Free Demo',
    'notFoundTitle': 'Module not found',
    'notFoundLink': 'Return to home',
    'otherModulesTitle': 'Other Modules',
    'otherModulesSubtitle': 'Discover how the AiRX platform manages all processes under one roof.',
    'otherModulesAllBtn': 'See All {{count}} Modules',
}

# ═══════════════════════════════════════════════
# blog — BlogPage.jsx
# ═══════════════════════════════════════════════
tr['blog'] = {
    'heroTitle': 'İK dünyasından içgörüler',
    'heroSubtitle': 'Mevzuat güncellemeleri, sektör rehberleri ve İK yönetimine dair pratik içerikler.',
    'featuredBadge': 'Öne Çıkan',
    'readBtn': 'Oku',
    'readSuffix': 'okuma',
    'catAll': 'Tümü',
    'emptyState': 'Bu kategoride henüz yazı yok.',
    'filterCount': '{{count}} yazı',
    'filterCountCat': '"{{cat}}" kategorisinde',
    'blogQuote': '"Biyometrik veri zorunluluk değil, tercih meselesidir."',
    'blogQuoteSource': 'AiRX · Mevzuat Rehberi',
    'readLabel': 'OKUMA',
}

en['blog'] = {
    'heroTitle': 'Insights from the HR World',
    'heroSubtitle': 'Regulatory updates, industry guides and practical content about HR management.',
    'featuredBadge': 'Featured',
    'readBtn': 'Read',
    'readSuffix': 'read',
    'catAll': 'All',
    'emptyState': 'No posts yet in this category.',
    'filterCount': '{{count}} posts',
    'filterCountCat': 'in "{{cat}}" category',
    'blogQuote': '"Biometric data is not a necessity, it\'s a choice."',
    'blogQuoteSource': 'AiRX · Compliance Guide',
    'readLabel': 'READ',
}

with open(r'c:\Users\pc\Desktop\airx\src\i18n\locales\tr.json', 'w', encoding='utf-8') as f:
    json.dump(tr, f, ensure_ascii=False, indent=2)
with open(r'c:\Users\pc\Desktop\airx\src\i18n\locales\en.json', 'w', encoding='utf-8') as f:
    json.dump(en, f, ensure_ascii=False, indent=2)

print('All remaining page keys added to tr.json and en.json successfully.')
