# -*- coding: utf-8 -*-
import json

with open(r'c:\Users\pc\Desktop\airx\src\i18n\locales\tr.json', encoding='utf-8') as f:
    tr = json.load(f)

with open(r'c:\Users\pc\Desktop\airx\src\i18n\locales\en.json', encoding='utf-8') as f:
    en = json.load(f)

tr['contact'] = {
  'heroTitle1': 'AiRX ekibiyle',
  'heroTitle2': 'dogrudan',
  'heroTitle3': 'baglanti kurun.',
  'heroSubtitle': 'Demo, teklif, kurulum yaklasimi veya urun detaylari icin bize ulasin. Ihtiyacinizi dinleyip size uygun akisi net ve hizli sekilde paylasalim.',
  'heroDemoBtn': 'Demo Talep Et',
  'heroCallBtn': 'Bizi Arayin',
  'step1': 'Ihtiyacinizi ve mevcut operasyon yapinizi dinliyoruz.',
  'step2': 'Size uygun modul setini ve kurulum yaklasimini paylasiyoruz.',
  'step3': 'Demo sonrasi gecis planini birlikte netlestiriyoruz.',
  'heroDemoDuration': '30-45 dk',
  'heroDemoDurationLabel': 'Ortalama demo suresi',
  'heroInstallDuration': '1 gun',
  'heroInstallDurationLabel': 'Hedef kurulum baslangici',
  'channel1Eyebrow': 'E-posta',
  'channel1Title': 'info@AiRX.com.tr',
  'channel1Text': 'Genel bilgi, teklif ve demo talepleriniz icin ekibimiz en kisa surede donus saglar.',
  'channel2Eyebrow': 'Telefon',
  'channel2Title': '+90 (216) 234 37 37',
  'channel2Text': 'Hafta ici mesai saatlerinde satis ve urun ekibimize dogrudan ulasabilirsiniz.',
  'channel3Eyebrow': 'Merkez Ofis',
  'channel3Title': 'Vadi Istanbul Park 7B, Sariyer',
  'channel3Text': 'Ayazaga Mah. Kemerburgaz Cad. Vadi Istanbul Park 7B Bilisim Vadisi K:2, Sariyer / Istanbul',
  'formTitle': 'Ekibimiz size en uygun akisi paylassin',
  'formSubtitle': 'Modul ihtiyaclarinizi, kullanici yapinizi ve kurulum beklentinizi birlikte degerlendirelim.',
  'formInfoText': 'Formu gonderdiginizde urun uzmanlarimiz sizinle iletisime gecer; modul ihtiyaclarinizi, kullanici yapinizi ve kurulum beklentinizi birlikte degerlendirir.',
  'formBullet1': 'Demo planlamasi',
  'formBullet2': 'Kurulum yaklasimi',
  'formBullet3': 'Modul eslestirmesi',
  'formBullet4': 'Ozel fiyat teklifi',
  'formDirectContact': 'Bize dogrudan yazin',
  'fieldName': 'Ad Soyad',
  'fieldNamePlaceholder': 'Adinizi girin',
  'fieldCompany': 'Sirket',
  'fieldCompanyPlaceholder': 'Sirket adi',
  'fieldEmail': 'E-posta',
  'fieldEmailPlaceholder': 'ornek@firma.com',
  'fieldPhone': 'Telefon',
  'fieldPhonePlaceholder': '+90 5xx xxx xx xx',
  'fieldSize': 'Calisan Sayisi',
  'fieldTopic': 'Konu',
  'fieldMessage': 'Mesajiniz',
  'fieldMessagePlaceholder': 'Kurum yapinizi ve ihtiyaclarinizi kisaca paylasabilirsiniz.',
  'fieldSelectPlaceholder': 'Seciniz',
  'size1': '20 ve alti',
  'size2': '20 - 100',
  'size3': '100 - 300',
  'size4': '300 - 1.000',
  'size5': '1.000 uzeri',
  'topic1': 'Urun demosu',
  'topic2': 'Fiyat / teklif',
  'topic3': 'Kurulum sureci',
  'topic4': 'Entegrasyon bilgisi',
  'topic5': 'Diger',
  'kvkkNote': 'Kisisel verileriniz KVKK kapsaminda korunmaktadir.',
  'submitButton': 'Talep Olustur',
  'faqTitle': 'Iletisim oncesi hizli cevaplar',
  'faqSubtitle': 'Ilk gorusme oncesinde en cok sorulan birkac basligi burada topladik.',
  'faq1q': 'Demo ne kadar surer?',
  'faq1a': 'Kurum yapiniza gore degismekle birlikte standart urun demosu genelde 30-45 dakika icinde tamamlanir.',
  'faq2q': 'Kurulum icin ek donanim gerekir mi?',
  'faq2a': 'Hayir. AiRX donanim zorunlulugu olmadan devreye alinabilir ve mevcut sureclerinize gore uyarlanir.',
  'faq3q': 'Teklif sureci nasil ilerler?',
  'faq3a': 'Ihtiyaciniz olan modul, kullanici sayisi ve operasyon kapsami netlestikten sonra size ozel teklif hazirlanir.',
  'faq4q': 'Hangi sektorlerle calisiyorsunuz?',
  'faq4a': 'Uretim, perakende, saglik, lojistik, hizmet sektoru basta olmak uzere personel operasyonu olan her kurumla calisiyoruz.',
  'ctaTitle': 'Size uygun paketi birlikte bulalim.',
  'ctaSubtitle': 'Calisan sayinizi ve ihtiyaclarinizi paylasin, satis ekibimiz en kisa surede size donus yapsin.',
  'ctaBtn1': 'Formu Doldur',
  'ctaBtn2': 'Hemen Ara'
}

en['contact'] = {
  'heroTitle1': 'Connect directly',
  'heroTitle2': 'with the',
  'heroTitle3': 'AiRX team.',
  'heroSubtitle': 'Reach out for a demo, quote, implementation approach or product details. We listen to your needs and share the right solution quickly.',
  'heroDemoBtn': 'Request a Demo',
  'heroCallBtn': 'Call Us',
  'step1': 'We listen to your needs and current operations structure.',
  'step2': 'We share the right module set and implementation approach for you.',
  'step3': 'We clarify the migration plan together after the demo.',
  'heroDemoDuration': '30-45 min',
  'heroDemoDurationLabel': 'Average demo duration',
  'heroInstallDuration': '1 day',
  'heroInstallDurationLabel': 'Target installation start',
  'channel1Eyebrow': 'Email',
  'channel1Title': 'info@AiRX.com.tr',
  'channel1Text': 'Our team responds promptly to general inquiries, quotes and demo requests.',
  'channel2Eyebrow': 'Phone',
  'channel2Title': '+90 (216) 234 37 37',
  'channel2Text': 'Reach our sales and product team directly during business hours on weekdays.',
  'channel3Eyebrow': 'Head Office',
  'channel3Title': 'Vadi Istanbul Park 7B, Sariyer',
  'channel3Text': 'Ayazaga Mah. Kemerburgaz Cad. Vadi Istanbul Park 7B IT Valley K:2, Sariyer / Istanbul',
  'formTitle': 'Let our team share the right solution for you',
  'formSubtitle': 'We will evaluate your module needs, user structure and implementation expectations together.',
  'formInfoText': 'Once you submit the form, our product experts contact you and evaluate your module needs, user structure and implementation expectations together.',
  'formBullet1': 'Demo scheduling',
  'formBullet2': 'Implementation approach',
  'formBullet3': 'Module matching',
  'formBullet4': 'Custom price quote',
  'formDirectContact': 'Write to us directly',
  'fieldName': 'Full Name',
  'fieldNamePlaceholder': 'Enter your name',
  'fieldCompany': 'Company',
  'fieldCompanyPlaceholder': 'Company name',
  'fieldEmail': 'Email',
  'fieldEmailPlaceholder': 'example@company.com',
  'fieldPhone': 'Phone',
  'fieldPhonePlaceholder': '+90 5xx xxx xx xx',
  'fieldSize': 'Employee Count',
  'fieldTopic': 'Topic',
  'fieldMessage': 'Your Message',
  'fieldMessagePlaceholder': 'You can briefly share your organization structure and needs.',
  'fieldSelectPlaceholder': 'Select',
  'size1': '20 or fewer',
  'size2': '20 - 100',
  'size3': '100 - 300',
  'size4': '300 - 1,000',
  'size5': '1,000+',
  'topic1': 'Product demo',
  'topic2': 'Pricing / quote',
  'topic3': 'Implementation process',
  'topic4': 'Integration info',
  'topic5': 'Other',
  'kvkkNote': 'Your personal data is protected under KVKK.',
  'submitButton': 'Submit Request',
  'faqTitle': 'Quick answers before reaching out',
  'faqSubtitle': 'We have compiled a few frequently asked questions to help before your first conversation.',
  'faq1q': 'How long does a demo take?',
  'faq1a': 'It varies by your organization, but a standard product demo is typically completed within 30-45 minutes.',
  'faq2q': 'Is additional hardware required for setup?',
  'faq2a': 'No. AiRX can be deployed without hardware requirements and is adapted to your existing processes.',
  'faq3q': 'How does the quoting process work?',
  'faq3a': 'Once your required modules, user count and scope are clarified, a custom quote is prepared for you.',
  'faq4q': 'Which industries do you work with?',
  'faq4a': 'We work with all organizations that have staff operations, including manufacturing, retail, healthcare, logistics and services.',
  'ctaTitle': "Let's find the right package for you.",
  'ctaSubtitle': 'Share your employee count and needs, and our sales team will get back to you as soon as possible.',
  'ctaBtn1': 'Fill the Form',
  'ctaBtn2': 'Call Now'
}

with open(r'c:\Users\pc\Desktop\airx\src\i18n\locales\tr.json', 'w', encoding='utf-8') as f:
    json.dump(tr, f, ensure_ascii=False, indent=2)

with open(r'c:\Users\pc\Desktop\airx\src\i18n\locales\en.json', 'w', encoding='utf-8') as f:
    json.dump(en, f, ensure_ascii=False, indent=2)

print('contact keys added to both files')
